### PR TITLE
Change sendCommand to public, to get acces to all Controls. e.g. Dimm…

### PR DESCRIPTION
**Pull request by patrick-dmxc**
…er, Status, RoomControler

### CODE REVIEW

**Comment by jimirocks** [comment]
Hello, many thanks for contribution!

 I would prefer to keep the method private and rather **introduce set of new usecase specific methods**, like current `sendControlPulse(On|Off)`, probably taking also some complex arguments (i.e. for dimmer). That way the library will be more intuitive and also safer.  If you can adjust your contribution this way, I will be happy to accept it.

If you really really need generic access, please use `LoxoneWebSocket` directly.

**Review by jimirocks — CHANGES_REQUESTED** [review]
as stated in above comment

**Comment by patrick-dmxc** [comment]
But in my opinion the location of "sendControlPulse(On|Off)" is not good in Loxone class
Its better located in the coresponding Controler class

**Comment by patrick-dmxc** [comment]
Like 
https://github.com/patrick-dmxc/loxone-java/commit/6c3bded7285342895c6f91eee8ed3a098d4a08a5

**Comment by jimirocks** [comment]
wow, that's a lot of code - I will look at it closer tommorow. Would be nice to add some coverage for new classes...

And to your idea - it's true that having all the `send` methods (for instance for Alarm) in `Loxone` class might be confusing in the end. But having them in control classes is also kinda weird - as they are just records now. Also designing it this way would allow sending command of some particular control to another miniserver (by passing the `loxone` argument to the method). So please let me think it over for day or two....

**Comment by jimirocks** [comment]
Also splitting `More controls` commit into more pull requests would  ease the review - if you can kindly do that.

**Comment by patrick-dmxc** [comment]
A other way to have the sendMethodes is by reference the loxone-instance into each Controler-Object when its created.

I yes i was a bit confused because there are only a few Controler-classes.

Im not this familiar with git, its quiet dificult to split this retrospectively.
May be its better if we decide together on a direction and then at the end I do a pull request

**Comment by jimirocks** [comment]
here is (one of many) guide for working with ommit retrospectively: https://about.gitlab.com/blog/2018/06/07/keeping-git-commit-history-clean/
For this situation 4th situation would be probably best fit.

**Comment by jimirocks** [comment]
Hello again. We discussed your proposal within team, and here is the result:
1. I adjusted the (obsolete) [README](https://github.com/Smarteon/loxone-java/pull/113) to clarify the `Loxone` class is the main interaction point.
2. We really don't want to introduce `send...` methods to `Control` classes - since they are basically just model classes not the interaction classes, also passing `loxone` as an argument is kind of unfortunate design from perspective of the library usage. So I  made [a proposal of new method](https://github.com/Smarteon/loxone-java/pull/113) to cover the complex use cases - possibly also generic string based command wouldn't be enough for some of them - please take a look if it suits your needs.
3. As for newly introduced control classes - please add them one by one in separate commits including unit tests
  * writing unit test should be kind of easy (but if you are unfamiliar with spock framework we use, just write them using junit5)
  * please try to study git to achieve the split - I believe it will pay you off, if you feel lost, I can help you - let's chat on some IM or video call in that case

**Comment by jimirocks** [comment]
@patrick-dmxc So what is your decision? Will you work in this further? Asking since you closed it, without any comment...

**Comment by patrick-dmxc** [comment]
I find that pretty unproductive. There are more important things than playing around in the git all night. So I'll go my own way.

**Comment by jimirocks** [comment]
well sorry about that - but when you want to contribute to OSS github you should learn the basics - I offered you help, which is more than usual...

Can we incorporate this code anyway? However, it's not our current priority, therefore it won't be immediate.

**Comment by patrick-dmxc** [comment]
you are welcome to cherrypick the code you want

**Comment by jimirocks** [comment]
Thanks, the controls will be in next release....

**Pull request closed without merging**
